[features]
seeds = false
[programs.localnet]
voting_contract = "CEgKUNC8VCEzQMz2WWXAYXgvBfmTHGPMZUXQSBBArkXk"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/jam1729/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
